config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:new, :show, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader

end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]
  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktails_path
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for cocktail, class: 'form' do |f| %>
  <%= f.input :name, label: 'Nombre del cocktail' %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/cocktails/edit.html.erb
<div class="container ">
 <div class= 'row justify-content-center'>
  <div class= 'col-md-8'>
    <h1>Editar a <%= @cocktail.name %></h1>
    <%= render 'form', cocktail: @cocktail %>
    <%= link_to "Volver al listado", cocktails_path %>
  </div>
</div>
</div>

app/views/cocktails/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon d-flex center justify-content-around">
  <%= link_to "#" do %>
  <%= image_tag "https://www.freelogodesign.org/file/app/client/thumb/92c62f69-8efa-4b41-99fb-1ecb1485854a_200x200.png?1572018860359", class:"nav-logo" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <h1  class="btn btn-light"><%= link_to "Agregar un cocktail", new_cocktail_path %></h1>
      </li>
    </ul>
  </div>
</div>
<div class="home-banner">
</div>

<div class="container ">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-12 col-md-6 col-lg-3">
      <div class="card-trip mb-3">
        <%= cl_image_tag cocktail.photo, alt: "alttext" %>
        <div class="card-trip-infos">
          <div>
            <h2><%= link_to cocktail.name, cocktail_path(cocktail) %></h2>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class= 'row justify-content-center'>
    <div class= 'col-md-8'>
      <h1>Crear un cocktail</h1>
      <%= render 'form', cocktail: @cocktail %>
      <%= link_to "Volver al listado", cocktails_path %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">

<%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>

  <h1> <%= @cocktail.name %></h1>
  <%= link_to "Volver al listado", cocktails_path %> |
  <%= link_to "Editar", edit_cocktail_path(@cocktail) %> |
  <%= link_to "Eliminar", cocktail_path(@cocktail), method: :delete, data: { confirm: "Seguro que desea elimnar un cocktail?"} %> |
  <%= link_to "Agregar una dose", new_cocktail_dose_path(@cocktail)  %> |
  <ul>
    <% @cocktail.doses.each do |dose| %>
    <li>
      <p><%= dose.description %> </p>
      <%= dose.ingredient.name %>
    </li>
    <%= link_to dose_path(dose), method: :delete, data: { confirm: "Seguro que desea elimnar un dose?"} do %>delete <% end %>
    <% end %>
  </ul>
</div>

app/views/doses/new.html.erb
<div class="container">
  <div class= 'row justify-content-center'>
    <div class= 'col-md-8'>
      <h1>Crear una dose</h1>
      <%= simple_form_for [@cocktail, @dose], class: 'form' do |f| %>
      <%= f.input :description%>
      <%= f.association :ingredient %>
      <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
      <%= link_to "Volver al listado", cocktails_path(@cocktail) %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>